# PIPELINE DEFINITION
# Name: train-test-split
# Inputs:
#    dataset_in: system.Dataset
#    test_size: float [Default: 0.2]
# Outputs:
#    dataset_test: system.Dataset
#    dataset_train: system.Dataset
components:
  comp-train-test-split:
    executorLabel: exec-train-test-split
    inputDefinitions:
      artifacts:
        dataset_in:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
      parameters:
        test_size:
          defaultValue: 0.2
          isOptional: true
          parameterType: NUMBER_DOUBLE
    outputDefinitions:
      artifacts:
        dataset_test:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        dataset_train:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-train-test-split:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - train_test_split
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.3.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef train_test_split(dataset_in: Input[Dataset],\n              \
          \       dataset_train: Output[Dataset],\n                     dataset_test:\
          \ Output[Dataset],\n                     test_size: float = 0.2):\n\n  \
          \  import pandas as pd\n    from sklearn.model_selection import train_test_split\n\
          \n    df = pd.read_csv(dataset_in.path)\n    df_train, df_test = train_test_split(df,\
          \ test_size=test_size, random_state=42)\n\n    df_train.to_csv(dataset_train.path,\
          \ index=False)\n    df_test.to_csv(dataset_test.path, index=False)\n\n"
        image: us-central1-docker.pkg.dev/dulcet-antler-403116/houseprice/houseprice_training:latest
pipelineInfo:
  name: train-test-split
root:
  dag:
    outputs:
      artifacts:
        dataset_test:
          artifactSelectors:
          - outputArtifactKey: dataset_test
            producerSubtask: train-test-split
        dataset_train:
          artifactSelectors:
          - outputArtifactKey: dataset_train
            producerSubtask: train-test-split
    tasks:
      train-test-split:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-train-test-split
        inputs:
          artifacts:
            dataset_in:
              componentInputArtifact: dataset_in
          parameters:
            test_size:
              componentInputParameter: test_size
        taskInfo:
          name: train-test-split
  inputDefinitions:
    artifacts:
      dataset_in:
        artifactType:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
    parameters:
      test_size:
        defaultValue: 0.2
        isOptional: true
        parameterType: NUMBER_DOUBLE
  outputDefinitions:
    artifacts:
      dataset_test:
        artifactType:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
      dataset_train:
        artifactType:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
schemaVersion: 2.1.0
sdkVersion: kfp-2.3.0
